language: node_js
node_js: node
sudo: required
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: GDJ+aAVFUFRn3Bk3GCmA+9tmNBmaXt9/tR86cd8BtnqFfue0OPwozszfOW5LaagjLjpwYzpPB/KZercLFM/oQRIKLPNfcYXM//pkWkXcZE5CCXfqfVvexGyi8ftRXD4MiCrJnZZ6j+yqElrAOW6jgOJ/mzc39NG4erluTyd/rs+Dr1pZeUVXPX2l7RovgNF8OnRXCCnwDPe5AYBymxcba81w5L9vpebxvyN4Nde0QdcGAJwkwFfcjcd/EBu0wQdIjIEy+QXusfbx1WkL1n73WIDyW7r5+ZtQesAqND7MfDE1XQRbIwi/HcwwTpf6GM3+4fo8VzWAlq/pEYJyfglGS1FLaqeo8yjAh7J7zOmHWFuu0hd1lvABB4LXhEiWZ0xvJd53WJWq8FbmmiPFvvVhJuVhcCbrtiAv8EdQKhKJFZVFrYIOK+GthEEZW7bSegblrt7W+ZFIlwXyB8uDS2/FpjKlXk9tqhs5OQQIEzOGJVro+KzOnkChAq9jKQIi0/TBNsOW+R1kUyeWNKjRiVUkHG+1JngyhEzthcTTBil71AIDPhOYH1DFKV9TTzIgUBg9w+iplb2WgTBThQM+F3TPzhm/M+pTa35F5qwiU3/7wsTqIHmVfDGpLy7y58yb3KTViPF+1l2NUpOffcVkbj5KaLzQ8q3BeUYFzkY3EjJGzYY=
  app: calm-journey-93197
  on:
    repo: codepressd/new-eddie-out
